jobs:
- job: Windows

  pool:
    vmImage: 'vs2017-win2016'

  strategy:
    matrix:
      node_10_x:
        node_version: 10.x
      node_11_x:
        node_version: 11.x

  steps:
  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      npm test --silent
    displayName: 'run test'

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: ./test-results.xml
      testRunTitle: 'test result'